services:
  db:
    image: postgres:14
    container_name: fitness_app_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persistent PostgreSQL data
#      - ./init-db:/docker-entrypoint-initdb.d/  # SQL script for initialization
volumes:
  postgres_data:
